version: '3.8'

services:
  # MySQL DB
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: product_list
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - ./.temp/mysql:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data:
    driver: local
