name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/dazzling-ego-445519-h3/api-repository/product-list:$GITHUB_SHA .
          docker push europe-west1-docker.pkg.dev/dazzling-ego-445519-h3/api-repository/product-list:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy product-list \
            --image europe-west1-docker.pkg.dev/dazzling-ego-445519-h3/api-repository/product-list:$GITHUB_SHA \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
